# Generated by Django 5.0.7 on 2024-07-28 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_item_description_remove_item_price_item_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Price_Band',
            new_name='Price',
        ),
    ]
