# Generated by Django 5.0.7 on 2024-07-28 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_price_band_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Price',
            new_name='Price_Band',
        ),
    ]
