# Generated by Django 5.0.7 on 2024-07-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_price_item_price_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Brand',
            field=models.CharField(default='Not Issued', max_length=255),
        ),
    ]
